### ISSUE TITLE
Zip inside zip with stored compression fails to open

### ISSUE THREAD

**Issue by mobad** [Majored/rs-async-zip#22]
[outer.zip](https://github.com/Majored/rs-async-zip/files/8987650/outer.zip)
I'm getting "failed to open reader: UnexpectedHeaderError(1969404127, 33639248)" when trying to open that file. (It was a larger zip but I created this test case)

I looked in to why it was happening and it looks like it's looking through the file starting at end-0xffff to end for the end of cd magic number. The problem is that since the inner zip isn't compressed by the outer zip it will actually find the inner zip's end of cd instead of the outer one.
It also runs in to problems if an arbitrary file has that byte sequence but that's probably a bit more rare.
[bad_bytes.zip](https://github.com/Majored/rs-async-zip/files/8987661/bad_bytes.zip)

I think the fix is to just make the AsyncDelimiterReader search starting from the end instead of the front of that range.

**Comment by Majored** [comment]
For the moment, I've altered it so that upon the match, the offset is stored & we continue reading until EOF whilst overwriting the offset when we encounter later EOCDHs. Afterward, we seek back to that last offset and continue where we left off.

This is the best solution I can see for the moment that doesn't require a big alteration in how finding the ECODH currently works. I've added a comment to revisit this in the future, but for the moment, this seems to work well. I've tested with the example ZIP you provided and that successfully reads.

Should be fixed with: https://github.com/Majored/rs-async-zip/commit/d9c44e1cf0e79c4a32e66111a2133bf889ee9b47

Let me know if you still run into issues.

**Comment by mobad** [comment]
Thanks! It seems to have fixed those zips but I'm still having issues with my real test case unfortunately.

It sometimes works and sometimes doesn't, really weird.
I believe it just happens to hit an edge case where the delimiter is split by two reads.

I've created another test case here, note its only really reproducible when you shrink the buffer size to 4<=n<8 (or some small primes) to help split reads across a delimiter.
[multiple_bad_bytes.zip](https://github.com/Majored/rs-async-zip/files/9031778/multiple_bad_bytes.zip)
(Just multiple delimiters with an extra byte in between.)

I've also included the original zip I was having issues with that should _intermittently_ fail with the default buffer size but will probably be easier to reproduce with some smaller numbers.
[test_created.zip](https://github.com/Majored/rs-async-zip/files/9031844/test_created.zip)

One issue I think is in AsyncDelimiterReader.
If you get a partial match at the end of the read_slice then you will lose those bytes as read_slice_len is < match_index + delimiter.len() and they won't get prepended.
I think just adding an else that prepends match_index.. would work.

Smaller issue is I think b.set_filled(match_index); should be using index instead so it returns an accurate count of bytes read (doesn't really matter as it isn't using the bytes read, but read_cd could potentially just do that to avoid the seeks to get the current offset)

Another potential issue (but won't happen with fixed buffer sizes I believe) is if you do a read, get a match, prepend remaining, then call read again but this time with a smaller buffer and it gets a match then there will still be bytes remaining in the prepend buffer when the new left over bytes are "prepended" they will be added to the end of the prepend buffer instead of the beginning which will corrupt the data.
I think prepend should check if buffer is empty and if it's not then prepend the new data, not extend.

I think some unit tests for AsyncDelimiterReader with small buffer sizes might make things easier to test as well.
